---
- name: Ensure Apache2 is installed and running
  hosts: all
  become: yes

  tasks:
    - name: Install Apache2 on RedHat-based systems
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Apache2 on Debian-based systems
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable Apache2 on RedHat-based systems
      ansible.builtin.systemd:
        name: httpd
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

    - name: Start and enable Apache2 on Debian-based systems
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started
      when: ansible_os_family == "Debian"
