---
- hosts: fedora 
  become: true
  become_method: sudo
  tasks:
  - name: Install PostgreSQL server and psycopg2
    ansible.builtin.dnf:
      name:
        - postgresql-server
        - postgresql-contrib
        - python3-psycopg2  
      state: present
      update_cache: true

  - name: Create the cluster
    ansible.builtin.command:
      cmd: postgresql-setup --initdb
      creates: /var/lib/pgsql/data/PG_VERSION

  - name: Start and enable the service
    ansible.builtin.systemd:
      name: postgresql
      state: started
      enabled: true

  - name: Ensure the PostgreSQL service is running
    ansible.builtin.systemd:
      name: postgresql
      state: started
      enabled: true
      
